Nop46/Nop.Plugin.Payments.Dpo/Controllers/PaymentDpoController.cs
using System;
using System.Collections.Specialized;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Payments;
using Nop.Plugin.Payments.Dpo.Models;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using System.Threading.Tasks;
using System.Xml.XPath;
using System.IO;

namespace Nop.Plugin.Payments.Dpo.Controllers
{
    public class PaymentDpoController : BasePaymentController
    {
        #region Fields

        private readonly IWorkContext _workContext;
        private readonly IStoreService _storeService;
        private readonly ISettingService _settingService;
        private readonly IOrderService _orderService;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly ILocalizationService _localizationService;
        private readonly DpoPaymentSettings _dpoPaymentSettings;
        private readonly IPermissionService _permissionService;
        private ILogger _logger;
        private INotificationService _notificationService;
        private IStoreContext _storeContext;

        private readonly String dpoLiveUrlV7 = "https://secure.3gdirectpay.com/API/v7/";

        #endregion

        #region Ctor

        public PaymentDpoController(
            IWorkContext workContext,
            IStoreService storeService,
            ISettingService settingService,
            IOrderService orderService,
            IOrderProcessingService orderProcessingService,
            ILocalizationService localizationService,
            IPermissionService permissionService,
            ILogger logger,
            DpoPaymentSettings dpoPaymentSettings,
            INotificationService notificationService,
            IStoreContext storeContext
            )
        {
            this._workContext = workContext;
            this._storeService = storeService;
            this._settingService = settingService;
            this._orderService = orderService;
            this._orderProcessingService = orderProcessingService;
            this._localizationService = localizationService;
            this._permissionService = permissionService;
            this._dpoPaymentSettings = dpoPaymentSettings;
            this._logger = logger;
            this._notificationService = notificationService;
            this._storeContext = storeContext;
        }

        #endregion

        #region Methods

        /// <summary>
        /// Handle push payment response from DPO
        /// </summary>
        /// <param name="form"></param>
        public async void DpoNotifyHandler()
        {
            // Notify DPO with OK response
            await Response.WriteAsync("OK");

            var formData = new NameValueCollection();
            using (var reader = new StreamReader(
                Request.Body,
                encoding: Encoding.UTF8,
                detectEncodingFromByteOrderMarks: false
                ))
            {
                var s = await reader.ReadToEndAsync();
                s = s.Replace("\\", "");
                var textReader = new StringReader(s);
                var response = new XPathDocument(textReader);
                var navigator = response.CreateNavigator();


                var reference = navigator.SelectSingleNode("//TransactionRef").Value;
                var trans_status = navigator.SelectSingleNode("//Result").Value;
                var transID = navigator.SelectSingleNode("//TransactionApproval").Value;
                var amount = navigator.SelectSingleNode("//TransactionAmount").Value;

                bool isPaid;

                await _logger.InformationAsync("DpoNotifyHandler start. Order no.: " + reference);

                Order order = await _orderService.GetOrderByIdAsync(Int32.Parse(reference));

                var verified = false;

                int orderId = 0;
                if (order != null)
                {
                    orderId = order.Id;
                }

                verified = order != null && amount == order.OrderTotal.ToString();
                await _logger.InformationAsync("DpoNotifyHandler: Order Payment Status: " + order.PaymentStatus);

                isPaid = order.PaymentStatus == PaymentStatus.Paid ? true : false;

                if (isPaid && verified)
                {
                    await _logger.InformationAsync("DpoNotifyHandler: Order no. " + reference + " is already paid");
                }

                if (!verified)
                {
                    trans_status = "900";
                }

                PaymentStatus query_status;
                var query_status_desc = "";

                switch (trans_status)
                {
                    case "000":
                        query_status = PaymentStatus.Paid;
                        query_status_desc = "Approved";
                        break;

                    case "900":
                        query_status = PaymentStatus.Pending;
                        query_status_desc = "Transaction result could not be verified";
                        break;

                    case "901":
                        query_status = PaymentStatus.Voided;
                        query_status_desc = "Declined";
                        break;

                    case "904":
                        query_status = PaymentStatus.Voided;
                        query_status_desc = "Cancelled By Customer with back button on payment page";
                        break;

                    default:
                        query_status = PaymentStatus.Voided;
                        query_status_desc = "Not Done";
                        break;
                }

                var sBuilder = new StringBuilder();

                sBuilder.AppendLine("Dpo Notify Handler");
                sBuilder.AppendLine("Dpo Query Data");
                sBuilder.AppendLine("=======================");
                sBuilder.AppendLine("Dpo Transaction_Id: " + transID);
                sBuilder.AppendLine("Dpo Status Desc: " + query_status_desc);
                sBuilder.AppendLine("");

                //order note
                await _orderService.InsertOrderNoteAsync(new OrderNote
                {
                    OrderId = orderId,
                    Note = sBuilder.ToString(),//sbbustring.Format("Order status has been changed to {0}", PaymentStatus.Paid),
                    DisplayToCustomer = false,
                    CreatedOnUtc = DateTime.UtcNow
                }); ;

                await _orderService.UpdateOrderAsync(order);

                //mark order as paid
                if (query_status == PaymentStatus.Paid)
                {
                    if (_orderProcessingService.CanMarkOrderAsPaid(order))
                    {
                        order.AuthorizationTransactionId = transID;
                        await _orderService.UpdateOrderAsync(order);

                        await _orderProcessingService.MarkOrderAsPaidAsync(order);
                    }
                    await _orderService.UpdateOrderAsync(order);
                    await _logger.InformationAsync("DpoNotifyHandler: Order marked paid");
                }
                else
                {
                    order.AuthorizationTransactionId = transID;
                    OrderNote note = new OrderNote();
                    note.OrderId = orderId;
                    note.CreatedOnUtc = DateTime.Now;
                    note.DisplayToCustomer = true;
                    note.Note = "Payment failed with the following description: " + trans_status;
                    await _logger.ErrorAsync("DpoNotifyHandler: Payment failed with the following description: " + trans_status);
                    if (_orderProcessingService.CanCancelOrder(order))
                    {
                        await _orderProcessingService.CancelOrderAsync(order, false);
                    }
                    await _orderService.InsertOrderNoteAsync(note);
                    await _orderService.UpdateOrderAsync(order);
                }
            }
        }

        /// <summary>
        /// Handle redirect response from DPO
        /// </summary>
        /// <param name="form"></param>
        /// <returns></returns>
        public async Task<IActionResult> DpoReturnHandler(IFormCollection form)
        {
            var reference = Request.Query["pgnopcommerce"];
            var transID = Request.Query["TransID"];
            var transToken = Request.Query["TransactionToken"];
            var client = new System.Net.WebClient();

            var trans_status = "";

            await _logger.InformationAsync("DpoReturnHandler start. Order no.: " + reference);
            var verified = false;
            var companyToken = _dpoPaymentSettings.CompanyToken;
            var serviceType = _dpoPaymentSettings.ServiceType;
            var dpoUrl = dpoLiveUrlV7;

            var order = await _orderService.GetOrderByIdAsync(Int32.Parse(Request.Query["pgnopcommerce"]));
            int orderId = 0;
            if (order != null)
            {
                orderId = order.Id;
            }


            //First query DPO with POST request
            var verifXML = new StringBuilder();
            verifXML.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>");
            verifXML.Append("<API3G>");
            verifXML.Append("<Request>verifyToken</Request>");
            verifXML.Append($"<CompanyToken>{companyToken}</CompanyToken>");
            verifXML.Append($"<TransactionToken>{transToken}</TransactionToken>");
            verifXML.Append($"<CompanyRef>{orderId}</CompanyRef>");

Nop46/Nop.Plugin.Payments.Dpo/Views/Configure.cshtml
@model Nop.Plugin.Payments.Dpo.Models.ConfigurationModel
@inject Nop.Core.IWebHelper webHelper
@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="PaymentDpo" asp-action="Configure" method="post">
    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">
                @Html.Raw(T("Plugins.Payments.Dpo.Instructions"))

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UseSSL_OverrideForStore" asp-input="UseSSL" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UseSSL" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseSSL" />
                        <span asp-validation-for="UseSSL"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="CompanyToken_OverrideForStore" asp-input="CompanyToken" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="CompanyToken" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="CompanyToken" />
                        <span asp-validation-for="CompanyToken"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="ServiceType_OverrideForStore" asp-input="ServiceType" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="ServiceType" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="ServiceType" />
                        <span asp-validation-for="ServiceType"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Nop46/Nop.Plugin.Payments.Dpo/Views/PaymentInfo.cshtml
@{
    Layout = "";
}
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <p><b>@T("Plugins.Payments.Dpo.Fields.RedirectionTip")</b></p>
        </td>
    </tr>
</table>